[storage]
# 存储后端类型，目前支持local
backend = "local"

[download_rules]
# 需要特殊处理的文件后缀列表
extensions = [
    "deb",
    "tar",
    "gz", 
    "xz",
    "rpm",
    "zip",
    "html",
    "md"
]

# 本地存储配置（当backend=local时生效）
[storage.local]
# 本地存储根目录
root_path = "/tmp/test-mirror-proxy"
